---
layout: post
title: "MY CE Journey"
date: 2026-03-29
categories: [General, Tech]
Intro:
"My name is Faryal Fatima and my journey to the Computer Engineering department at UET Faisalabad wasn't just an academic pursuit; it was a battle for survival. It started with the sweat and stress of the ECAT, the dream of securing a seat. When I finally got that admission, I thought the hard part was over. I was wrong. Here I was, a fresher in a new city, alone in a hostel, grappling with a trauma that felt impossible to process while being thrown into the deep end of practical labs and co-education dynamics. This portfolio isn't just about learning to code; it's about learning to stand up when life tries to bury you. It’s the story of how I turned grief into grit, one lecture and lab project at a time."




